---
title: 'Request for change'
body: 
- type: markdown
  attributes:
    value: "# Request for change form"

- type: checkboxes
  id: change-source
  attributes:
    label: Change source
    description: Check all that apply
    options: 
      - label: New feature
      - label: Feature enhancement
      - label: Dependencies
      - label: Defect
      - label: Security
      - label: Legal
      - label: Other
      
- type: checkboxes
  id: change-area
  attributes:
    label: Area of change
    options:
      - label: Architecture
      - label: Automation
      - label: Documentation
      - label:  Existing feature
      - label: New feature
      - label: Versioning
      - label: Other

- type: textarea
  id: reason
  attributes:
    label: Reason for change
    description: What problem is this solving, how will this improve current process, etc..
  validations:
    required: true
    
- type: textarea
  id: value-add
  attributes:
    label: Value added
  validations:
    required: true

- type: textarea
  id: risk-add
  attributes:
    label: Risk introduced
  validations:
    required: true
    
- type: textarea
  id: change-description
  attributes:
    label: Change description
    description: Be as technical as you'd like here
  validations:
    required: true
    
- type: textarea
  id: support-docs
  attributes:
    label: Supporting documentation
    description: LucidChart diagrams, package documentation, etc..
  validations:
    required: true
    
- type: dropdown
  id: jira-ticket
  attributes: 
    label: Will these changes require a new JIRA ticket?
    options: 
     - Yes
     - No
  validatons:
    required: true
---
