---
title: 'Request for change'
body: 
- type: markdown
  attributes:
    value: "# Request for change form

### Change source (select all that apply)
- [ ] New feature
- [ ] Feature enhancement
- [ ] Dependencies
- [ ] Defect
- [ ] Security
- [ ] Legal
- [ ] Other (please specify): _______________________

### Area of change
- [ ] Architecture
- [ ] Automation
- [ ] Documentation
- [ ] Existing feature (please specify): _______________________
- [ ] New feature
- [ ] Versioning
- [ ] Other (please specify): _______________________

### Reason for change (What problem is this solving, how will this improve current process, etc..)"
- type: input
  id: reason
  attributes:
    label: Reasoning
  validations:
    required: true
    
- type: markdown
  attributes:
    value: "


### Value added


### Risk introduced


### Change description (Be as technical as you'd like here)


### Supporting documentation (LucidChart diagrams, package documentation, etc..)


### Will these changes require a new Jira ticket?
"
---
